mail:
  domain: gmail.com

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: password
    driver-class: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update  
