mail:
  domain: gmail.com

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://103.21.53.12:3306/spawalk
    username: root
    password: Lms@401<hunk
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    packages-to-scan : com.spawalk



# Notification FCM 
notification:
       auth-key: AAAA_m3sceU:APA91bF5ZqwAwWZCjd__i0CtVcfucast_o3ayt_rlHzHiBTeMtuvA3geHAySeHsjX9QFrXE86avdn1S24yLVmkU5OH3ZDAvu_Ve5VTLA5OIzXB__ADyLyi14QnB96p3GZt8RAviJSjPz
       fmc-url: https://fcm.googleapis.com/fcm/send
      


# SMS Keys MSG91
sms:
  auth-key: 275903AM8R9RlOaa5cd42b46
  sender-id: SpaWak
  route: 4
  main-url: http://api.msg91.com/api/sendhttp.php?

# Email Config
email:
  from-mail: admin@spawalk.com
  password: spa@401hunk
  host: smtp.gmail.com
  port: 465
  auth: true
  
