mail:
  domain: gmail.com

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://103.21.53.12:3306/spawalk
    username: root
    password: Lms@401<hunk
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    packages-to-scan : com.spawalk
